### PR TITLE
remove misc index from online docs

### PR DESCRIPTION
**Pull request by smikes**
Simple, safe, fast, easy, and effective.

Candidate fix for #102

### CODE REVIEW

**Comment by linclark** [comment]
Thanks Sam! @zeke, what do you think? Do we want to wait until we have the redirection from #94 in, or do we just want to 404 it for now?

**Comment by smikes** [comment]
I tried to find a list of pages that link to docs.npmjs.com/misc/index but apparently Google no longer supports the `link:` operator?

Anyway.  Can be held indefinitely, no rush.

**Comment by zeke** [comment]
Yeah let's hold off shipping this until I wrap up #94. Thanks for getting the ball rolling, @smikes

**Comment by smikes** [comment]
:+1:

**Pull request merged**
